use_colour: false

modification_unary_rules: false
only_np_topicalisation_valid: false
restrictive_absorption: false
curly_vars: false
vp_nongap_topicalisation: true

debug_vars: false
show_vars: false
debug: false

low_key_debug: false
aug_pprint: false
#cmd_reader_class: AugmentedPTBReader
cmd_reader_class: GuessReader
cn_puncts: true
cn_rules: true
use_modes: false
headed_cats: true
hatted_cats: false
highlight_head_arrows: true
fail_on_unassigned_variables: false
use_csc: true

use_bare_N: false
use_sb_alias: true
lcp_to_np_typechange: true
punct_cued_typechange: true
merge_verb_compounds: true
