modification_unary_rules: false
only_np_topicalisation_valid: false
restrictive_absorption: true
curly_vars: false
show_vars: false
#show_vars: true
#debug: false
debug: true
low_key_debug: false
aug_pprint: true
#aug_pprint: false
cmd_reader_class: AugmentedPTBReader
#cmd_reader_class: GuessReader
cn_puncts: true
cn_rules: true
use_modes: false
headed_cats: true
