modification_unary_rules: false
only_np_topicalisation_valid: false
restrictive_absorption: false
curly_vars: false
lcp_to_np_typechange: true
vp_nongap_topicalisation: false

debug_vars: false
show_vars: false
debug: true

low_key_debug: false
aug_pprint: false
#cmd_reader_class: AugmentedPTBReader
cmd_reader_class: GuessReader
cn_puncts: true
cn_rules: true
use_modes: false
headed_cats: true
highlight_head_arrows: true
fail_on_unassigned_variables: false
